version: 2

dependencies:
  pre:
    - pip install awscli

jobs:
  build:
    docker:
      - image: circleci/node:6.10
      - image: circleci/python:3.6.4


    working_directory: ~/ec2-autostop

    steps:
      - checkout
      - run : pip install awscli
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test

  deploy:
    steps:
      - run:
          command: |
            ./publish_lambda.sh